version: '3.8'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    networks:
      - database
    restart: always
    env_file: ./.env.development
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - "./mongodb/dev:/data/db"

  node-app-dev:
    depends_on:
      - mongodb
    env_file: ./.env.development
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - database
      - proxy
    ports:
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./backend/app.js:/backend/app.js
      - ./backend/controllers:/backend/controllers
      - ./backend/middleware:/backend/middleware
      - ./backend/models:/backend/models
      - ./backend/routes:/backend/routes

  react-app-dev:
    depends_on:
      - node-app-dev
    env_file: ./.env.development
    networks:
      - proxy
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - $REACT_PORT:$REACT_PORT
    volumes:
      - './frontend/public:/frontend/public'
      - './frontend/src:/frontend/src'

  nginx:
      restart: always
      depends_on:
        - react-app-dev
        - node-app-dev
        - mongodb
      networks:
       - proxy
      build:
        context: ./nginx
        args:
          - NODE_PORT=$NODE_PORT
          - REACT_PORT=$REACT_PORT
          - SERVER_NAME=$SERVER_NAME
          - MODE=$MODE
      ports:
        - 80:80

networks:
  proxy:
  database:
