version: "3.8"

services:
  mongodb:
    image: docker.io/bitnami/mongodb:latest
    networks:
      - database
    restart: always
    env_file: ./.env.production
    environment:
      - "MONGODB_PORT_NUMBER=$DB_PORT"
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - "./mongodb/prod:/bitnami/mongodb"

  node-app:
    depends_on:
      - mongodb
    build: ./backend
    networks:
      - proxy
      - database
    restart: unless-stopped
    env_file: ./.env.production
    ports:
      - $NODE_PORT:$NODE_PORT

  react-app:
    depends_on:
      - node-app
    build:
      context: ./frontend
    networks:
      - proxy
    env_file: ./.env.production
    ports:
      - $REACT_PORT:$REACT_PORT

  nginx:
    depends_on:
      - react-app
      - node-app
      - mongodb
    build:
      context: ./nginx
      args:
        - NODE_PORT=$NODE_PORT
        - REACT_PORT=$REACT_PORT
        - SERVER_NAME=$SERVER_NAME
    networks:
      - proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  proxy:
  database:
